---
name: Daniel
surname: Rodríguez
position: "Ph.D. Student"
address: "JMU-Würzburg, Biocentre, Office C015"
phone: 0931 31-82967
#profilepic: Mifoto.jpg
#www: "researchgate.net/profile/Daniel-Rodriguez-Leon"
email: "daniel.rodriguez@uni-wuerzburg.de"
orcid: 0000-0001-9637-1364
researchgate: Daniel-Rodriguez-Leon
linkedin: dsrodriguezl
github: dsrodriguezl
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "870000"
papersize: letterpaper
# "5D2B7E"
# aboutme: "I am Daniel Sebastián Rodríguez León, a colombian biologist with a great interest in Behavioral and Chemical Ecology, in particular towards the study of Social Organization and Evolution, as well as Animal Communication."
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(vitae)
library(dplyr)
library(tibble)

readExcelSheets <- function(filename){
  library(readxl)
  sheets <- excel_sheets(here::here("EN", filename))
  sheets_list <- lapply(sheets
                       , function(x) read_excel(
                         here::here(
                           "EN", filename)
                         , sheet = x))
  names(sheets_list) <- sheets
  list2env(sheets_list, envir = .GlobalEnv)
}

readExcelSheets("cv_data.xlsx")
```

# Higher Education

```{r}
education |> 
  detailed_entries(with =  Degree, what = Institution, when = Year, where = Where, why = detail, .protect = F)
```

# Professional Experience

```{r}
experience |> 
  detailed_entries(with = Title, what = Unit, when = Year, where = Where, why = detail, .protect = F)
```

# Continuing Education

```{r}
continuing_education |> 
  detailed_entries(with =  Degree, what = Institution, when = Year, where = Where, why = detail, .protect = F)
```

# Publications

```{r}
bibliography_entries("publications.bib") |>
  arrange(desc(author$family), issued)
```

# Conference contributions

```{r}
conferences |> 
  detailed_entries(with =  Title, what = Unit, when = Year, where = Where, why = detail
                   , .protect = F)
```

# Stipends and Awards

```{r}
stipends_awards |>  
  detailed_entries(with = Type, what = Institution, when = Year, where = Where, .protect = F)

```

# Voluntary work

```{r}
volunteering |>  
  detailed_entries(with = Type, what = Institution, when = Year, where = Where, .protect = F)

```


# Additional Qualifications

```{r}
qualifications |> 
  brief_entries(when = Area, what = Qualification, .protect = F)
```

