---
name: Daniel
surname: Rodriguez
position: "Ph.D. Student"
address: "JMU-Wuerzburg"
email: "daniel.rodriguez@stud-mail.uni-wuerzburg.de "
orcid: 0000-0001-9637-1364
www: https://www.researchgate.net/profile/Daniel-Rodriguez-Leon
linkedin: dsrodriguezl
github: dsrodriguezl
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I am a biologist with a great interest in Behavioral and Chemical Ecology"
docname: CV
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Higher Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~Detail,
  "Bachelor of Science Biology", "2011-2016", "Universidad Nacional de Colombia", "Bogota, Colombia", "Bachelor thesis: Variation of the relative abundance and diet of dogs (Canis lupus familiaris) on a gradient of human presence in a natural preserve of the civil society (Tabio, Cundinamarca).",
  "Master of Science Biosciences", "2017-2020", "Julius-Maximilians-Universitaet Wuerzburg", "Wuerzburg, Germany", "Master thesis: Variation of cuticular hydrocarbon profiles among honeybee workers from different European subspecies."
) %>% 
  detailed_entries(Degree, Year, Institution, Where, Detail)
```

# Professional experience

# Continuing Education

# Publications

```{r}
library(dplyr)

bibliography_entries("bib.bib") %>%
  arrange(desc(author$family), issued)
```

# Additional Qualifications

```{r}
tribble(
  ~Area, ~Qualification, ~Proficiency,
  "Software", "Microsoft Office (Word, Excel, PowerPoint, oneNote)", "Good knowledge (User)",
  "Software", "R", "Basic knowledge",
  "Software", "RMarkdown", "Basic knowledge",
  "Software", "Git", "Beginner",
  "Software", "Markdown", "Beginner",
  "Languages", "Spanish", "Mother tongue",
  "Languages", "English", "Advance (C1)",
  "Languages", "German", "Intermediate (B2)"
) %>% 
  brief_entries(Area, Qualification, Proficiency)
```
