---
name: Daniel
surname: Rodríguez
position: "Ph.D. Student"
address: "JMU-Wuerzburg"
#phone: 
#profilepic: Mifoto.jpg #The photo is not properly adjusted
#www: "researchgate.net/profile/Daniel-Rodriguez-Leon"
email: "daniel.rodriguez@stud-mail.uni-wuerzburg.de"
orcid: 0000-0001-9637-1364
researchgate: Daniel-Rodriguez-Leon
linkedin: dsrodriguezl
github: dsrodriguezl
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I am Daniel Sebastián Rodríguez León, a colombian biologist with a great interest in Behavioral and Chemical Ecology, in particular towards the study of Social Organization and Evolution, as well as Animal Communication."
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(vitae)
```

# Higher Education

```{r}
library(tibble)
tribble(
   ~ Degree,  ~ Year, ~ Institution,  ~ Where, ~ detail,
  "Bachelor of Science Biology", "2011 - 2016", "Universidad Nacional de Colombia", "Bogotá, Colombia", NA,
  "Master of Science Biosciences", "2017 - 2020", "Julius-Maximilians-Universitaet Wuerzburg",  "Wuerzburg, Germany", NA
) %>% 
  detailed_entries(with =  Degree, what = Institution, when = Year, where = Where, why = detail)
```

# Professional Experience

```{r}
library(tibble)
tribble(
  ~ Title, ~Unit, ~ Year, ~ Where, ~detail,
  "Internship", "Biodiversity Sciences program of the Line of Risk Assessment and Wildlife, Instituto Alexander von Humboldt", "August 2016 - February 2017", "Bogotá, Colombia", NA,
  
) %>% 
  detailed_entries(with = Title, what = Unit, when = Year, where = Where, why = detail)
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

